# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8432fdebeb0cafb03adf8985dde4e760982a2076c088c0bfbb27647940434aff876e603c53261a11a96feb3f5da886ab905ff2210eddc892f3cd8698957014b4
  email_provider_username: <%= ENV["ronyfhebrian"]
  email_provider_password: <%= ENV["qhc-nG4-EEy-ouk"]
  domain_name: acehbus.com
  mailchimp_api_key: <%= ENV["4f746ec9c70e89c6917c10d91d240b09-us12"]
  mailchimp_list_id: <%= ENV["06566afba2"] %>
  owner_email: <%= ENV["rfhebrian@gmail.com"] %>

test:
  secret_key_base: 9d347a94446f792cb47862ffe1b6ba8718f4dff2d4542ab63614a0ed31c39f0a18745fcaa0ff81c4f5e9e386975f7123037072a20c21f8a913006677e8220137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
